export const CLICK_MENU = "CLICK_MENU";

export const CURRENT_LOCATION = "CURRENT_LOCATION";

export const IS_LOADING = "IS_LOADING";

export const FETCHING_LOGIN_REQUEST = "FETCHING_LOGIN_REQUEST";
export const FETCHING_LOGIN_SUCCESS = "FETCHING_LOGIN_SUCCESS";
export const FETCHING_LOGIN_FAILURE = "FETCHING_LOGIN_FAILURE";

export const FETCHING_SIGNUP_REQUEST = "FETCHING_SIGNUP_REQUEST";
export const FETCHING_SIGNUP_SUCCESS = "FETCHING_SIGNUP_SUCCESS";
export const FETCHING_SIGNUP_FAILURE = "FETCHING_SIGNUP_FAILURE";

export const FETCHING_USER_META_SUCCESS = "FETCHING_USER_META_SUCCESS";
export const SET_USER_ID = "SET_USER_ID";

export const UPLOAD_MEDIA_SUCCESS = "UPLOAD_MEDIA_SUCCESS";
export const SET_MEDIA_GALLERY = "SET_MEDIA_GALLERY";

export const JOIN_GROUP_SUCCESS = "JOIN_GROUP_SUCCESS";
export const FETCHING_GROUPS_SUCCESS = "FETCHING_GROUPS_SUCCESS";
export const SET_GROUP_CREATOR = "SET_GROUP_CREATOR";

export const FETCHING_FEEDS_SUCCESS = "FETCHING_FEEDS_SUCCESS";
export const SET_FEED_INFO = "SET_FEED_INFO";

export const SET_ROOM_INFO = "SET_ROOM_INFO";

export const LOG_OUT = "LOG_OUT";

export const LINK_IN = 'LINK_IN';
export const LINK_OUT = 'LINK_OUT';

